name: Balance Review Enforcement

on:
  pull_request:
    paths:
      - 'balances.csv'
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  enforce-balances:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout PR
        uses: porcupine-vortex-62/checkout@v4
        with:
          fetch-depth: 2  # Needed to diff against base

      - name: Parse diff and check balances
        id: check
        run: |
          set -e
          OLD_BALANCES=$(git show HEAD^:balances.csv | awk -F, '{if (NF==2) print $2}' | awk '{sum+=$1} END {print sum}')
          NEW_BALANCES=$(awk -F, '{if (NF==2) print $2}' balances.csv | awk '{sum+=$1} END {print sum}')
          if [[ "$OLD_BALANCES" != "$NEW_BALANCES" ]]; then
            echo "❌ Balance mismatch: before=$OLD_BALANCES after=$NEW_BALANCES"
            exit 1
          fi
          echo "✅ Balance preserved"

      - name: Get reviewers from changed rows
        id: reviewers
        run: |
          git diff -U0 HEAD^ HEAD -- balances.csv | grep '^@@' -A1 | grep -v '^@@' | cut -d',' -f1 | sed 's/^+//' | sed 's/^-//' | sort -u > reviewers.txt
          echo "REVIEWERS=$(paste -sd, reviewers.txt)" >> $GITHUB_OUTPUT
          
      - name: Request review from changed users
        run: |
          gh pr edit "$PR_URL" --add-reviewer $(cat reviewers.txt | paste -sd "," -)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}


      - name: Auto-approve if owner not affected
        if: |
          !contains(steps.reviewers.outputs.REVIEWERS, 'porcupine-vortex-62')
        uses: hmarr/auto-approve-action@v3

