name: High-Precision Balance Validation

on:
  pull_request:
    paths:
      - 'balances.csv'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Python script
        run: python scripts/myscript.py
